spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chathub
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: dev
      password: "@uthU$eR12"
    
server:
  port: 8182